name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/Checkout@v4
            - name: Printing folder
              run: ls
            - name: Setup Node
              uses: actions/setup-Node@v3
              with:
                node-version:   '20.x'
            #- name: Install dependency
              #run: npm ci

        # 0. Checkout the code
        # 1. install a dependency
        # 2. Execute automated test