name: 05 - 1 - Event Filter and Ativity Types

on:
    pull_request: 
        types: 
            - opened
            - synchronize
        branches: 
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running wherever a PR is opened or synchronized and base branch is main"